[package]
name = "rustpress"
bin-package = "rustpress"
lib-package = "rustpress"
site-root = "target/site"
site-pkg-dir = "pkg"
style-file = "style/main.css"
assets-dir = "public"
site-addr = "127.0.0.1:8080"
reload-port = 3001
browserquery = "defaults"

[lib]
default-features = false
features = ["hydrate"]

[bin]
default-features = false
features = ["ssr"]
